callr::rscript("data-raw/1-z22.R")
callr::rscript("data-raw/cleanup.R")
callr::rscript("data-raw/2-z11_100m_import.R")
callr::rscript("data-raw/3-z11_100m_split.R")
callr::rscript("data-raw/cleanup.R")
callr::rscript("data-raw/4-z11_1km.R")
callr::rscript("data-raw/5-grids.R")
